# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Workshop' do
pod 'Socket.IO-Client-Swift', '~> 5.5.0'
pod 'Alamofire', '~> 3.0'
end

target 'WorkshopTests' do

end

